Repository alisharify7/preconfigured-docker-compose, pull requests merged in 2025-07, with the labels that each got.

#42 Add PostgreSQL and PgAdmin configurations; update MSSQL version
  database/postgres-pgadmin/.env.sample
  database/postgres-pgadmin/docker-compose.yaml
  database/sqlserver/.env.sample
Labels: bug, enhancement

#43 add authentik #5
  auth/authentik/.env.sample
  auth/authentik/docker-compose.yaml
Labels: enhancement

#44 Update readme
  README.md
Labels: documentation
